### PR TITLE
Oneclick deploy button

### PR DESCRIPTION
**Pull request by devkiran**

### CODE REVIEW

**Comment by devkiran** [comment]
@niwsa Can you do a quick check?

**Comment by niwsa** [comment]
Not able to test ... I think since the repo is private both heroku and vercel is not able to deploy...

**Comment by deepakprabhakara** [comment]
@niwsa No worries, let's wait for you to sort out the env vars. Then I can cleanup the certs and make it public

**Comment by deepakprabhakara** [comment]
Merging it in to rewrite history

**Pull request merged**
