### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by devkiran**

### CODE REVIEW

**Comment by devkiran** [comment]
Have to pass the env variables, need to test after moving the cert as env.

**Review by deepakprabhakara — APPROVED** [review]
LGTM

**Comment by deepakprabhakara** [comment]
@devkiran You'll also need to add Github actions to build and push this. I'll create the container registry now. You can follow Jackson.

**Comment by devkiran** [comment]
@deepakprabhakara Yes, I will do it.

**Comment by deepakprabhakara** [comment]
Merging it in to rewrite history

**Pull request merged**
